//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextChallenge.Database {
    using NextChallenge.Helpers;
    using System;

    public partial class Topic {

        public System.Guid IdTopic { get; set; }
        public System.Guid IdUser { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsActive { get; set; }

        public virtual User User { get; set; }
        public Topic()
        {
            IdTopic = Guid.NewGuid();
            CreateDate = DateTime.Now;
            IsActive = true;
            IdUser = Keys.IdUser;
        }
    }
}
